const IC={home:'<path d="M3 11 12 3l9 8v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',book:'<path d="M2 4h6a4 4 0 0 1 4 4v13a3 3 0 0 0-3-3H2zM22 4h-6a4 4 0 0 0-4 4v13a3 3 0 0 1 3-3h7z"/>',task:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M9 15l2 2 4-4"/>',cal:'<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',inbox:'<path d="M22 12h-6l-2 3h-4l-2-3H2"/><path d="M5.5 5.1 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.5-6.9A2 2 0 0 0 16.7 4H7.3a2 2 0 0 0-1.8 1.1z"/>',star:'<path d="m12 2 3 6.9 7.5.7-5.6 5 1.7 7.4L12 18l-6.6 4 1.7-7.4-5.6-5 7.5-.7z"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0"/>',out:'<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9"/>',search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>',play:'<path d="m6 3 14 9-14 9z"/>',x:'<path d="M18 6 6 18M6 6l12 12"/>',down:'<path d="m6 9 6 6 6-6"/>',right:'<path d="m9 6 6 6-6 6"/>',eye:'<path d="M2 12s4-8 10-8 10 8 10 8-4 8-10 8S2 12 2 12z"/><circle cx="12" cy="12" r="3"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1-1.1a5.5 5.5 0 0 0-7.8 7.8l1 1.1L12 21l7.8-7.5 1-1.1a5.5 5.5 0 0 0 0-7.8z"/>',msg:'<path d="M21 11.5a8.4 8.4 0 0 1-12.4 7.4L3 21l2-5.4A8.4 8.4 0 1 1 21 11.5z"/>',ok:'<circle cx="12" cy="12" r="10"/><path d="m8 12 3 3 5-6"/>',no:'<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6M9 9l6 6"/>',cap:'<path d="m22 10-10-5L2 10l10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/>',trophy:'<path d="M6 9H4a2 2 0 0 1-2-2V5h4M18 9h2a2 2 0 0 0 2-2V5h-4M6 3h12v7a6 6 0 0 1-12 0zM12 16v3M8 22h8"/>',cards:'<rect x="3" y="3" width="8" height="8" rx="1"/><rect x="13" y="3" width="8" height="8" rx="1"/><rect x="3" y="13" width="8" height="8" rx="1"/><rect x="13" y="13" width="8" height="8" rx="1"/>',ext:'<path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6M15 3h6v6M10 14 21 3"/>',clock:'<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',plus:'<path d="M12 5v14M5 12h14"/>',send:'<path d="m22 2-7 20-4-9-9-4zM22 2 11 13"/>',mon:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>',fold:'<path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/>',info:'<circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/>',refresh:'<path d="M3 12a9 9 0 0 1 15-6.7L21 8M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16M3 21v-5h5"/>'};
const ic=n=>`<svg class="i" viewBox="0 0 24 24">${IC[n]||''}</svg>`,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const ring=(p,c,s=76,fs='1rem',w=7)=>{const r=(s-w)/2,L=2*Math.PI*r;return `<div class="ring" style="width:${s}px;height:${s}px;--fs:${fs}"><svg width="${s}" height="${s}"><circle class="t" cx="${s/2}" cy="${s/2}" r="${r}" stroke-width="${w}"/><circle class="v" cx="${s/2}" cy="${s/2}" r="${r}" stroke-width="${w}" stroke="${c}" stroke-dasharray="${L}" stroke-dashoffset="${L}" data-to="${L*(1-p/100)}"/></svg><b>${p}%</b></div>`};
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('on');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('on'),2200)};
/* data */
const ME={name:'Joud El Daher',first:'Joud',ini:'JE',sub:'IGCSE · Year 12'};
const SCHED={0:['pr','7:00 PM'],2:['th','7:00 PM'],4:['pr','2:30 PM'],5:['th','7:00 PM']};const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],TODAY=2;
const ASG=[{t:'aaa',st:'Submitted',lv:'Hard',due:'4/10, 06:16 PM',ty:'task',se:'practical',mx:20,sc:null,desc:'aaaa',sub:'Submitted 4/10/2026'},{t:'Ch1',st:'Graded',lv:'Medium',due:'4/11, 11:38 PM',ty:'classified',se:'theory',mx:30,sc:28},{t:'Chapter 1',st:'Submitted',lv:'Medium',due:'7/4, 02:00 AM',ty:'classified',se:'theory',mx:100,sc:null,sub:'Submitted 7/4/2026'}];
const PH_V=[['Phase 1',['CH 1 Computer Structure','CH 2 Input Devices','CH 3 Output Devices','CH 4 Storage Devices']],['Phase 2',['CH 6 P1 Networks','CH 6 P2 Networks','CH 7 Malware Attacks']],['Phase 3',['CH 8 SDLC','CH 9 ICT Systems','CH 10 Banking Applications','CH 11 ICT Applications','CH 12 ICT Programs','CH 13 ICT Effects']]];
const PH_N=[['Phase 1',['CH 1 Computer Structure','CH 2 Input Devices','CH 3 Output Devices','CH 4 Storage Devices']],['Phase 2',['CH 5 Database','CH 6 Networks','CH 7 Malware Attacks']],['Phase 3',['CH 8 SDLC','CH 9 ICT Systems','CH 10 Banking applications','CH 11 ICT Applications','CH 12 ICT Programs','CH 13 ICT Effects']]];
const PRAC=[['Microsoft Word',2],['Microsoft PowerPoint',2],['Microsoft Access',4],['Microsoft Excel',4],['Microsoft SharePoint',4]];
const CARDS=[['Define Computer','An electronic device that accepts data, processes it using instructions and outputs information.'],['Name two input devices','Keyboard and microphone.'],['What does RAM stand for?','Random Access Memory — temporary, volatile working memory.']];
const ANN=[{t:'Test Announcment',k:'general',lv:'Medium',b:'Heloooooooooooo',d:'Aug 27',by:'Ahmad Tamer',v:14,l:0,c:[]}];
const WA=[['Welcome back','Your plan is 93% complete — keep the streak alive.']];
/* shell */
$('#side').innerHTML=`<div class="brand"><span class="lg"><img class="lgi" src="assets/logo-full.webp" alt="AT-ICT"></span></div>`+[['home','Home','home'],['learn','Learn','book'],['work','Work','task',3],['schedule','Schedule','cal'],['inbox','Inbox','inbox',1]].map(n=>`<button class="nv" data-v="${n[0]}">${ic(n[2])}${n[1]}${n[3]?`<span class="bd">${n[3]}</span>`:''}</button>`).join('')+`<div class="pts"><small>My points · Oct 26</small><b>${ic('star')}0 <span style="font-size:.85rem;color:var(--mu);font-family:var(--font-body);font-weight:400">pts</span></b><div class="bar"><i style="width:4%"></i></div><small style="text-transform:none;letter-spacing:0">Complete work to climb the board</small></div>`;
$('#tabbar').innerHTML=[['home','Home','home'],['learn','Learn','book'],['work','Work','task',3],['schedule','Schedule','cal'],['inbox','Inbox','inbox',1]].map(n=>`<button data-v="${n[0]}">${ic(n[2])}${n[1]}${n[3]?`<span class="bd">${n[3]}</span>`:''}</button>`).join('');
$('#top').innerHTML=`<span class="lg m mlogo"><img class="lgi" src="assets/logo-mark.png" alt="AT-ICT"></span><h2 id="ttl"></h2><span class="sp"></span><button class="ib" aria-label="Notifications" id="bell">${ic('bell')}<span class="dot"></span></button><button class="ib" aria-label="Log out">${ic('out')}</button><div class="me"><span class="av">${ME.ini}</span><div><b>${ME.name}</b><small>${ME.sub}</small></div></div>`;
/* HOME */
const lb=[['a1','JE','Joud El Daher (you)',1],['a2','YT','Yousuf Tarek'],['a3','YD','yousef Dawoud']];
$('#v-home').innerHTML=`<div class="hero"><div><span class="eb">Welcome back</span><h1 class="big">Hi ${ME.first} — let's get that <em>A*.</em></h1><p class="sub">You're 93% through this term's plan. Keep the streak alive.</p><div class="acts"><button class="btn p" data-go="work">${ic('task')}3 assignments pending</button><button class="btn o" data-go="learn">${ic('play')}Continue learning</button></div></div>${ring(93,'#ff3b66',140,'1.7rem',12)}</div>
<div class="g4">${[['Assignments','task','3/6',50,'#60a5fa','<span class="bad">3 pending</span>'],['Quizzes','cap','0/0',0,'#a3a3ab','<span style="color:var(--fa)">None yet</span>'],['Attendance','cal','3/6',50,'#a78bfa','<span class="ok">All done ✓</span>'],['Avg. score','trophy','28%',28,'#fbbf24','<span class="ok">Graded work</span>']].map(s=>`<div class="stat"><div><small>${ic(s[1])}${s[0]}</small><b>${s[2]}</b>${s[5]}</div>${ring(s[3],s[4],68,'.85rem',6)}</div>`).join('')}</div>
<div class="g2"><div class="card"><h3>${ic('clock')}Up next<button class="lk" data-go="schedule">Full schedule →</button></h3>
<div class="next"><div class="tm">7:00<small>PM today</small></div><div><h4>Excel Guide 3</h4><p>7:00 – 8:30 PM · <span class="chip c-th">Theory</span></p></div><button class="btn p sm" data-toast="Opening session…">Join</button></div>
<div class="next"><div class="tm">Fri<small>2:30 PM</small></div><div><h4>Practical session</h4><p><span class="chip c-pr">Practical</span></p></div></div>
<div class="next"><div class="tm" style="color:#fb7185">4/10<small>Overdue</small></div><div><h4>aaa</h4><p>Hard · practical · awaiting grade</p></div><button class="btn o sm" data-go="work">View</button></div></div>
<div class="card"><h3>${ic('trophy')}Leaderboard<button class="lk" aria-label="Refresh" data-toast="Leaderboard refreshed">${ic('refresh')}</button></h3>${lb.map((l,i)=>`<div class="lb ${l[3]?'me2':''}"><i>0${i+1}</i><span class="av ${l[0]}">${l[1]}</span><b style="${l[3]?'color:#ff7d98':''}">${l[2]}</b><span class="pt">0</span></div>`).join('')}</div></div>
<div class="g2" style="grid-template-columns:.9fr 1.1fr"><div class="card"><h3>${ic('inbox')}Latest announcement<button class="lk" data-go="inbox">View all →</button></h3><button class="ann" data-ann="0" style="margin:0"><h4>Test Announcment <span class="chip c-th">Notice</span></h4><p>Heloooooooooooo</p><div class="m"><span>Aug 27</span><span>Ahmad Tamer</span></div></button></div>
<div class="card"><h3>${ic('cal')}This week</h3><div class="week" id="wk"></div></div></div>`;
const full=()=>DAYS.map((d,i)=>`<div class="wd ${i===TODAY?'today':''}"><small>${d}</small>${SCHED[i]?`<div class="ev ${SCHED[i][0]==='th'?'th':'pr'}"><b>${SCHED[i][0]==='th'?'Theory':'Practical'}</b>${SCHED[i][1]}</div>`:'<span class="no">—</span>'}</div>`).join('');
$('#wk').innerHTML=DAYS.map((d,i)=>`<div class="wd ${i===TODAY?'today':''}"><small>${d}</small>${SCHED[i]?`<div class="ev ${SCHED[i][0]==='th'?'th':'pr'}"><b>${SCHED[i][0]==='th'?'TH':'PR'}</b>${SCHED[i][1].replace(':00','').replace(' PM','p')}</div>`:'<span class="no">—</span>'}</div>`).join('');
/* LEARN */
const acc=(arr,mk)=>arr.map((p,i)=>`<div class="acc"><button><span class="n">${i+1}</span><span><h4>${p[0]}</h4><small>${p[1].length} ${mk.u}</small></span>${ic('down')}</button><div class="bd3"><div><div class="in">${p[1].map((c,k)=>mk.f(c,i,k)).join('')}</div></div></div></div>`).join('');
const pcol=['#60a5fa','#34d399','#a78bfa'];
$('#v-learn').innerHTML=`<div class="ph"><h1>Everything you study, in one place</h1></div>
<div class="seg" id="lseg">${[['mat','fold','Materials'],['vid','play','Videos'],['not','book','Notes'],['fla','cards','Flashcards']].map((s,i)=>`<button data-s="${s[0]}" class="${i?'':'on'}">${ic(s[1])}${s[2]}</button>`).join('')}</div>
<div class="sub-v on" id="s-mat"><div class="search">${ic('search')}<input placeholder="Search materials…" aria-label="Search materials" id="msearch"></div><div class="chips" id="mchips">${[['Theory',1],['Practical',1],['Other',0]].map((c,i)=>`<button class="ch ${i?'':'on'}">${c[0]}<em>${c[1]}</em></button>`).join('')}</div><div id="mshelf"></div></div>
<div class="sub-v" id="s-vid"><div class="chips">${['Theory','Practical','Other'].map((c,i)=>`<button class="ch vf ${i?'':'on'}" data-f="${c}">${c}</button>`).join('')}</div><div id="vph"></div><div id="vpr" style="display:none"></div><div id="vot" style="display:none"></div></div>
<div class="sub-v" id="s-not"><div id="nph"></div></div>
<div class="sub-v" id="s-fla"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px;flex-wrap:wrap"><p class="sub">Study and create flashcard stacks</p><button class="btn p sm" data-toast="Stack editor coming up">${ic('plus')}Create stack</button></div><div class="stats4">${[['Total stacks',1,'file'],['Teacher stacks',0,'cap'],['Student stacks',1,'cards'],['Total cards',3,'task']].map(s=>`<div class="stat"><div><small>${s[0]}</small><b>${s[1]}</b></div></div>`).join('')}</div><div class="fc-g"><button class="item" id="openfc" style="padding:18px"><span style="display:grid;gap:6px;text-align:left"><span class="chip c-pr" style="justify-self:start">Student · 3 cards</span><b style="font-size:1.05rem">Chapter 1</b><small>0 studies · ${ME.name}</small></span>${ic('eye')}</button></div></div>`;
/* WORK */
const asgRow=a=>{const g=a.st==='Graded';return `<div class="row"><button class="hd"><span class="ic">${ic('task')}</span><div><h4>${a.t}<span class="chip ${g?'c-pr':'c-th'}">${a.st}</span><span class="chip ${a.lv==='Hard'?'c-rd':'c-am'}">${a.lv}</span></h4><div class="meta"><span>Due <b class="due">${a.due}</b></span><span>Type <b>${a.ty}</b></span><span>Section <b>${a.se}</b></span></div></div><div class="sc"><div><small>Score</small><b class="${g?'ok':''}">${a.sc??'—'}/${a.mx}</b>${g?`<em>${Math.round(a.sc/a.mx*100)}%</em>`:''}</div><span class="chip c-gy">Details ${ic('down')}</span></div></button><div class="dt"><div><div class="dtin"><div><div class="lbl">Instructions</div><div class="box">${a.desc||'No instructions provided.'}</div></div><div><div class="lbl">Submission</div>${g?`<div class="box gr"><b>${ic('ok')} Graded</b><p style="margin-top:6px">Score: <b style="color:#fff">${a.sc}/${a.mx} (${Math.round(a.sc/a.mx*100)}%)</b></p></div>`:`<div class="box bl"><b>${ic('clock')} Awaiting grade</b><p style="margin-top:6px;color:var(--mu)">${a.sub}</p></div>`}</div></div></div></div></div>`};
$('#v-work').innerHTML=`<div class="ph"><span class="eb">Assignments &amp; quizzes</span><h1>Your work</h1></div><div class="seg" id="wseg"><button data-s="asg" class="on">${ic('task')}Assignments</button><button data-s="qz">${ic('cap')}Quizzes</button></div>
<div class="sub-v on" id="s-asg"><div class="card" style="margin-bottom:16px;display:flex;justify-content:space-between;align-items:center;gap:14px;flex-wrap:wrap"><div><div class="sum"><span class="ok">${ic('ok')}3 completed</span><span class="bad">${ic('no')}3 pending</span></div></div><button class="btn p sm" data-toast="Up to date">${ic('refresh')}Refresh</button></div>${ASG.map(asgRow).join('')}</div>
<div class="sub-v" id="s-qz"><div class="card" style="margin-bottom:16px;display:flex;justify-content:space-between;align-items:center;gap:14px;flex-wrap:wrap"><div class="sum"><span class="ok">${ic('ok')}0 completed</span><span class="bad">${ic('no')}1 pending</span></div><button class="btn p sm" data-toast="Up to date">${ic('refresh')}Refresh</button></div>
<div class="row open"><button class="hd"><span class="ic">${ic('cap')}</span><div><h4>Test<span class="chip c-rd">Not started</span><span class="chip c-am">${ic('clock')} 00:09:00</span></h4><div class="meta"><span>Date <b>10/7</b></span><span>Time <b>22:20</b></span><span>Duration <b>10 min</b></span></div></div><div class="sc"><div><small>Score</small><b>—/30</b></div><span class="btn g sm" data-toast="Quiz starts when you confirm" role="button">${ic('play')}Start quiz</span></div></button><div class="dt"><div><div class="dtin" style="grid-template-columns:1fr 1fr"><div><div class="lbl">Instructions</div><div class="box">No instructions provided.</div></div><div><div class="lbl">Quiz status</div><div class="box gr"><b>${ic('ok')} Ready</b> — click “Start quiz” to begin</div></div></div></div></div></div></div>`;
/* SCHEDULE */
$('#v-schedule').innerHTML=`<div class="ph" style="display:flex;justify-content:space-between;align-items:flex-end;gap:14px;flex-wrap:wrap"><div><span class="eb">Class timetable</span><h1>Weekly schedule</h1></div><div class="seg" style="margin:0" id="sseg"><button class="on">Week</button><button>Day</button></div></div>
<div class="card"><div class="week" id="wk2" style="grid-template-columns:repeat(7,minmax(0,1fr))"></div></div>
<div class="sch-g"><div class="card"><h3>${ic('clock')}Today — Wednesday</h3><div class="next" style="background:rgba(96,165,250,.1);border-color:rgba(96,165,250,.3)"><span class="ic" style="width:44px;height:44px;border-radius:12px;background:#2563eb;display:grid;place-items:center">${ic('book')}</span><div><h4>Excel Guide 3</h4><p>7:00 PM — 8:30 PM</p></div><span class="chip c-th" style="margin-left:auto">Theory</span></div></div>
<div class="card"><h3>${ic('task')}Upcoming sessions</h3><div class="ups"><div class="up"><span class="chip c-th">Theory</span><b style="display:block;margin-top:8px;font-family:var(--font-numeric)">7:00 PM</b><small>Wed, Oct 7</small></div><div class="up"><span class="chip c-pr">Practical</span><b style="display:block;margin-top:8px;font-family:var(--font-numeric)">2:30 PM</b><small>Fri, Oct 9</small></div></div></div></div><p class="sub" style="text-align:center;margin-top:24px;font-size:.82rem;color:var(--fa)">Last updated August 10, 2026</p>`;
$('#wk2').innerHTML=full();
/* INBOX */
const annHtml=()=>ANN.map((a,i)=>`<button class="ann" data-ann="${i}"><h4>${ic('info')} ${a.t}<span class="chip c-th">${a.lv}</span></h4><p>${a.b}</p><div class="m"><span>${a.d}</span><span>${a.by}</span><span>${ic('eye')}${a.v}</span><span>${ic('heart')}${a.l}</span><span>${ic('msg')}${a.c.length}</span></div></button>`).join('');
$('#v-inbox').innerHTML=`<div class="ph"><span class="eb">Stay in the loop</span><h1>Inbox</h1></div><div class="seg" id="iseg"><button data-s="an" class="on">${ic('inbox')}Announcements</button><button data-s="ch">${ic('msg')}Chat</button></div>
<div class="sub-v on" id="s-an"><div class="search">${ic('search')}<input placeholder="Search announcements…" aria-label="Search"></div><div class="chips">${[['All',1],['General',1],['Assignment',0],['Exam',0],['Holiday',0],['Meeting',0],['Important',0]].map((c,i)=>`<button class="ch ${i?'':'on'}">${c[0]}<em>${c[1]}</em></button>`).join('')}</div><div id="annl">${annHtml()}</div></div>
<div class="sub-v" id="s-ch"><div class="chat"><div class="chl"><button class="on"><span class="av">AT</span><span><b>Class group</b><small>Ahmad: See you Wednesday</small></span></button><button><span class="av" style="background:#2563eb">AT</span><span><b>Ahmad Tamer</b><small>Teacher · direct</small></span></button></div><div class="cm"><div class="cmh">Class group</div><div class="cmb" id="cmb"><div class="bub">Remember to bring your Excel files to Wednesday's session.<small>Ahmad Tamer · 10:12 AM</small></div><div class="bub mine">Will do, thank you!<small>You · 10:20 AM</small></div></div><form class="cmf" id="cmf"><input class="inp" style="border-radius:99px" placeholder="Type a message…" aria-label="Message"><button class="btn p" aria-label="Send">${ic('send')}</button></form></div></div></div>`;
/* routing */
const T={home:'Home',learn:'Learn',work:'Work',schedule:'Schedule',inbox:'Inbox'};let cur='home';
function go(v){cur=v;$$('.view').forEach(e=>e.classList.toggle('on',e.id==='v-'+v));$$('[data-v]').forEach(b=>b.classList.toggle('on',b.dataset.v===v));$('#ttl').textContent=T[v];scrollTo({top:0});localStorage.setItem('at-portal-v',v);setTimeout(()=>$$('.ring .v',$('#v-'+v)).forEach(c=>c.style.strokeDashoffset=c.dataset.to),60)}
document.addEventListener('click',e=>{const t=e.target.closest('[data-v],[data-go],[data-toast],[data-ann],.acc>button,.node,[data-cont],.row>.hd,.seg button[data-s],.ch');if(!t)return;
if(t.dataset.v)go(t.dataset.v);else if(t.dataset.go)go(t.dataset.go);else if(t.dataset.toast&&!t.closest('.row>.hd .btn')){toast(t.dataset.toast)}else if(t.dataset.toast)toast(t.dataset.toast);
else if(t.dataset.ann!==undefined)openAnn(+t.dataset.ann);
else if(t.matches('.node,[data-cont]'))openNode(t);
else if(t.matches('.acc>button'))t.parentElement.classList.toggle('cl');
else if(t.matches('.row>.hd')){if(!e.target.closest('[data-toast]'))t.parentElement.classList.toggle('open')}
else if(t.matches('.seg button[data-s]')){const sg=t.parentElement,pre=sg.id==='lseg'?'s-':sg.id==='wseg'?'s-':'s-';$$('button',sg).forEach(b=>b.classList.toggle('on',b===t));$$('.sub-v',sg.parentElement).forEach(s=>{if(s.parentElement===sg.parentElement)s.classList.toggle('on',s.id===pre+t.dataset.s)})}
else if(t.matches('.ch')){$$('.ch',t.parentElement).forEach(b=>b.classList.toggle('on',b===t));if(t.classList.contains('vf')){const M={Theory:'vph',Practical:'vpr',Other:'vot'};Object.entries(M).forEach(([k,v])=>$('#'+v).style.display=k===t.dataset.f?'':'none')}}});
$$('.row').forEach((r,i)=>{if(i===3)r.classList.add('open')});
/* modals */
const modal=h=>{const m=$('#mod');m.innerHTML=`<div class="dlg" role="dialog">${h}</div>`;m.classList.add('on');document.body.style.overflow='hidden';const x=$('.x',m);x&&(x.onclick=closeM)};const closeM=()=>{$('#mod').classList.remove('on');document.body.style.overflow=''};
$('#mod').onclick=e=>{if(e.target.id==='mod')closeM()};addEventListener('keydown',e=>e.key==='Escape'&&closeM());
function openAnn(i){const a=ANN[i];const cm=()=>a.c.map(c=>`<div class="cmt"><span class="av" style="width:34px;height:34px">J</span><div class="box" style="flex:1;padding:10px 14px">${c}</div></div>`).join('');
modal(`<button class="ib x" aria-label="Close">${ic('x')}</button><h3 style="display:flex;gap:10px;align-items:center;font-size:1.3rem;font-family:var(--font-body);letter-spacing:0;padding-right:50px">${ic('info')}${a.t}</h3><div style="display:flex;gap:10px;margin:10px 0 18px;align-items:center;color:var(--fa);font-size:.85rem"><span class="chip c-th">${a.lv}</span>${a.by} · ${a.d}</div><div style="padding:18px 0;border-block:1px solid var(--bd)">${a.b}</div><div style="display:flex;gap:14px;align-items:center;margin:16px 0"><button class="btn o sm" id="lk">${ic('heart')}<span>${a.l} Likes</span></button><span style="color:var(--fa);font-size:.88rem;display:flex;gap:6px;align-items:center">${ic('eye')}${a.v} Views</span></div><h4 style="font-family:var(--font-body);letter-spacing:0">Comments (<span id="cn">${a.c.length}</span>)</h4><div id="cl">${cm()}</div><form class="cmt" id="cf"><span class="av" style="width:34px;height:34px;background:rgba(202,19,62,.25);color:#ff7d98">J</span><input class="inp" placeholder="Add a comment…" aria-label="Comment" style="flex:1"><button class="btn p sm">Post</button></form>`);
$('#lk').onclick=()=>{a.l=a.l?0:1;$('#lk span').textContent=a.l+' Likes';$('#lk').style.borderColor=a.l?'var(--cr)':'';$('#annl').innerHTML=annHtml()};
$('#cf').onsubmit=e=>{e.preventDefault();const v=e.target.querySelector('input');if(!v.value.trim())return;a.c.push(v.value.trim());v.value='';$('#cl').innerHTML=cm();$('#cn').textContent=a.c.length;$('#annl').innerHTML=annHtml()}}
$('#openfc').onclick=()=>{let i=0;const draw=()=>{modal(`<button class="ib x" aria-label="Close">${ic('x')}</button><h3 style="font-family:var(--font-body);letter-spacing:0">Chapter 1</h3><p class="sub">General · 3 cards · By ${ME.name}</p><div class="fcard" id="fcd"><div><div class="f fr"><span>${CARDS[i][0]}<small>Click to flip</small></span></div><div class="f bk"><span>${CARDS[i][1]}</span></div></div></div><div style="display:flex;justify-content:space-between;align-items:center"><button class="btn o sm" id="pv" ${i?'':'disabled style="opacity:.4"'}>Previous</button><span class="sub">${i+1} of 3</span><button class="btn o sm" id="nx" ${i<2?'':'disabled style="opacity:.4"'}>Next</button></div>`);$('#fcd').onclick=e=>e.currentTarget.classList.toggle('fl');$('#pv').onclick=()=>{i--;draw()};$('#nx').onclick=()=>{i++;draw()}};draw()};
$('#cmf').onsubmit=e=>{e.preventDefault();const v=e.target.querySelector('input');if(!v.value.trim())return;$('#cmb').insertAdjacentHTML('beforeend',`<div class="bub mine">${v.value.replace(/</g,'&lt;')}<small>You · now</small></div>`);v.value='';$('#cmb').scrollTop=1e5};
go(localStorage.getItem('at-portal-v')&&T[localStorage.getItem('at-portal-v')]?localStorage.getItem('at-portal-v'):'home');

