[build]
builder = "DOCKERFILE"
dockerfilePath = "railway.Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 10
numReplicas = 1

[service]
internal_port = 5000
auto_deploy_on = ["main"] 