/* ---------- INBOX ---------- */
R.inbox=()=>{const s=S.inb,unread=CHATS.reduce((a,c)=>a+c.unread,0);$('#v-inbox').innerHTML=`<div class="ph pr"><div><span class="eb">Stay in the loop</span><h1>Inbox</h1></div>${s.tab==='ann'?`<button class="btn p" data-act="qAnn">${ic('plus')}Create announcement</button>`:''}</div>${seg([['ann','Announcements','mega',ANN.length],['chat','Chat','msg',unread||''],['sess','Sessions','wifi']],s.tab,'inbTab')}<div id="ibody"></div>`;({ann:annView,chat:chatView,sess:sessView})[s.tab]()};
ACT.inbTab=t=>{S.inb.tab=t.dataset.arg;rerender()};
function annView(){const pub=ANN.length,pinned=ANN.filter(a=>a.pin).length,urg=ANN.filter(a=>a.pr==='urgent').length;
$('#ibody').innerHTML=`<div class="g4">${[['Total','mega',pub],['Published','ok',pub],['Pinned','pin',pinned],['Urgent','alert',urg]].map(s=>`<div class="stat"><div><small>${ic(s[1])}${s[0]}</small><b>${s[2]}</b></div></div>`).join('')}</div>${ANN.length?ANN.map((a,i)=>`<div class="card ann-c"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><h3 style="margin:0">${a.t}</h3><span class="chip c-th">${a.cat}</span><span class="chip ${a.pr==='urgent'?'c-rd':'c-am'}">${a.pr}</span>${a.pin?'<span class="chip c-gy">Pinned</span>':''}<span class="lact" style="margin-left:auto"><button class="ib sm dng" data-act="annDel" data-arg="${i}" aria-label="Delete">${ic('trash')}</button></span></div><p class="sub" style="margin:8px 0">${esc(a.b)}</p><div class="rg-m"><span>${ic('cal')}${a.d}</span><span>${ic('users')}${a.aud}</span><span>${ic('eye')}${a.v} views</span></div></div>`).join(''):empty('No announcements yet.','mega')}`}
ACT.annDel=t=>confirmM('Delete this announcement?','Delete',()=>{ANN.splice(+t.dataset.arg,1);rerender();toast('Deleted')});
function chatView(){const s=S.inb,c=CHATS.find(x=>x.id===s.chat)||CHATS[0];
$('#ibody').innerHTML=`<div class="chat ${s.cm?'open':''}"><div class="chl">${CHATS.map(x=>`<button class="${x.id===c.id?'on':''}" data-act="chatSel" data-arg="${x.id}"><span class="av">${ini(x.n)}</span><span><b>${x.n}</b><small>${x.sub}</small></span>${x.unread?`<span class="bd" style="margin-left:auto">${x.unread}</span>`:''}</button>`).join('')}</div><div class="cm"><div class="cmh"><button class="ib sm back-m" data-act="chatBack" aria-label="Back">${ic('left')}</button>${c.n}</div><div class="cmb" id="cmb">${c.m.map(m=>`<div class="bub ${m[0]==='t'?'mine':''}">${esc(m[1])}<small>${m[0]==='t'?'You':m[3]||''} · ${m[2]}</small></div>`).join('')}</div><form class="cmf" id="cmf"><input class="inp" style="border-radius:99px" placeholder="Type a message…" aria-label="Message"><button class="btn p" aria-label="Send">${ic('send')}</button></form></div></div>`;
$('#cmf').onsubmit=e=>{e.preventDefault();const i=e.target.querySelector('input');if(!i.value.trim())return;c.m.push(['t',i.value.trim(),'now']);i.value='';chatView()};const b=$('#cmb');b.scrollTop=1e5}
ACT.chatSel=t=>{S.inb.chat=t.dataset.arg;S.inb.cm=1;CHATS.find(x=>x.id===t.dataset.arg).unread=0;rerender()};ACT.chatBack=()=>{S.inb.cm=0;rerender()};
function sessView(){const s=S.inb,on=Object.values(LAST).filter(x=>x[1]).length;
$('#ibody').innerHTML=`<div class="g4">${[['Total students','users',STU.length],['Active sessions','wifi',on],['Online students','ok',on],['Offline students','block',STU.length-on]].map(x=>`<div class="stat"><div><small>${ic(x[1])}${x[0]}</small><b>${x[2]}</b></div></div>`).join('')}</div><div class="fbar"><div class="chips" style="margin:0">${['All','Online','Offline'].map(c=>`<button class="ch ${s.sf===c?'on':''}" data-act="sessF" data-arg="${c}">${c}</button>`).join('')}</div><div class="search" style="margin:0;flex:1;min-width:200px">${ic('search')}<input data-in="sessQ" placeholder="Search student…" value="${esc(s.sq)}" aria-label="Search"></div></div><div class="card" style="padding:8px" id="sessl"></div>`;sessRows()}
function sessRows(){const s=S.inb,q=s.sq.toLowerCase();const l=STU.filter(x=>{const o=(LAST[x.n]||[])[1]?1:0;return(!q||x.n.toLowerCase().includes(q))&&(s.sf==='All'||(s.sf==='Online')===!!o)});
$('#sessl').innerHTML=l.length?l.map(x=>{const o=(LAST[x.n]||[])[1];return `<div class="srow2"><span class="av" style="width:40px;height:40px">${ini(x.n)}<i class="dotp ${o?'on':''}"></i></span><div class="lmain"><b>${x.n}</b><small>${x.em}</small></div><span class="en-c">${LAST[x.n]?LAST[x.n][0]:'Never logged in'}</span><span class="chip ${o?'c-pr':'c-gy'}">${o?'1 session':'Offline'}</span>${o?`<button class="ib sm dng" data-act="revoke" data-arg="${esc(x.n)}" aria-label="End session">${ic('out')}</button>`:'<span style="width:38px"></span>'}</div>`}).join(''):empty('No students match.','users')}
ACT.sessF=t=>{S.inb.sf=t.dataset.arg;rerender()};INP.sessQ=t=>{S.inb.sq=t.value;sessRows()};
ACT.revoke=t=>confirmM(`End ${t.dataset.arg}'s session?`,'End session',()=>{LAST[t.dataset.arg][1]=0;rerender();toast('Session ended')});
