/* ---------- LIBRARY ---------- */
const LT=[['videos','Videos','play',()=>VIDS],['notes','Interactive notes','lib',()=>NOTES],['mats','Materials','fold',()=>MATS],['flash','Flashcards','cards',()=>FLASH.map(f=>({t:f.t,path:[f.kind+' stacks'],f}))],['site','Website content','star',()=>[]]];
const pathStr=(p,a)=>(a||[]).slice(0,p.length).join('|')===p.join('|');
R.library=()=>{const l=S.lib;$('#v-library').innerHTML=`<div class="ph pr"><div><span class="eb">Content library</span><h1>Library</h1></div><button class="btn p" data-act="libAdd">${ic('plus')}Add ${({videos:'video',notes:'note',mats:'material',flash:'stack',site:'entry'})[l.tab]}</button></div>${seg(LT.map(t=>[t[0],t[1],t[2],t[0]==='site'?'':t[3]().length]),l.tab,'libTab')}<div id="lbody"></div>`;l.tab==='site'?siteView():libView()};
ACT.libTab=t=>{S.lib.tab=t.dataset.arg;S.lib.path=[];S.lib.q='';rerender()};
ACT.libAdd=()=>({videos:vidModal,notes:noteModal,mats:matModal,flash:flashModal,site:()=>toast('Use the forms below')})[S.lib.tab]();
function treeHTML(items){const l=S.lib,sel=l.path,nodes=new Map();items.forEach(it=>it.path.forEach((_,i)=>{const k=it.path.slice(0,i+1).join('|');nodes.set(k,{p:it.path.slice(0,i+1),n:(nodes.get(k)?.n||0)+1})}));
const show=n=>n.p.length<=2||pathStr(n.p.slice(0,-1),sel)||pathStr(sel,n.p.slice(0,-1));
return `<button class="tn l0 ${sel.length?'':'on'}" data-act="tree" data-arg=""><span>All ${LT.find(t=>t[0]===l.tab)[1].toLowerCase()}</span><em>${items.length}</em></button>`+[...nodes.values()].filter(show).map(n=>`<button class="tn l${n.p.length} ${sel.join('|')===n.p.join('|')?'on':''}" data-act="tree" data-arg="${esc(n.p.join('|'))}"><span>${esc(n.p[n.p.length-1])}</span><em>${n.n}</em></button>`).join('')}
function libView(){const l=S.lib,items=LT.find(t=>t[0]===l.tab)[3]();$('#lbody').innerHTML=`<div class="lib"><details class="treebox card" ${innerWidth>900?'open':''}><summary>${ic('fold')}Browse by phase / chapter</summary><div id="tree">${treeHTML(items)}</div></details><div><div class="fbar"><div class="search" style="margin:0;flex:1">${ic('search')}<input data-in="libQ" placeholder="Search ${LT.find(t=>t[0]===l.tab)[1].toLowerCase()}…" value="${esc(l.q)}" aria-label="Search library"></div><span class="sub" id="lcount"></span></div><div class="card" style="padding:8px"><div id="ll"></div></div></div></div>`;libRows()}
function libRows(){const l=S.lib,items=LT.find(t=>t[0]===l.tab)[3](),q=l.q.toLowerCase(),f=items.filter(it=>pathStr(l.path,it.path)&&(!q||(it.t+it.path.join(' ')).toLowerCase().includes(q)));$('#lcount').textContent=`${f.length} of ${items.length}`;
$('#ll').innerHTML=f.length?f.map(it=>{const k=items.indexOf(it),warn=l.tab==='notes'&&!it.url;return `<div class="lrow"><span class="lic">${ic(({videos:'play',notes:'lib',mats:'fold',flash:'cards'})[l.tab])}</span><div class="lmain"><b>${hl(it.t,q)}</b><small>${it.path.join(' › ')}${it.order!==undefined?` · Order ${it.order}`:''}${it.meta?' · '+it.meta:''}</small></div>${warn?'<span class="chip c-am">No link yet</span>':it.url?`<span class="url">${ic('link')}prezi.com</span>`:''}${l.tab==='flash'?`<span class="chip c-gy">${it.f.cards} cards · by ${it.f.by}</span>`:''}<div class="lact"><button class="ib sm" data-act="libEdit" data-arg="${k}" aria-label="Edit">${ic('edit')}</button><button class="ib sm dng" data-act="libDel" data-arg="${k}" aria-label="Delete">${ic('trash')}</button></div></div>`}).join(''):empty('Nothing here. Try clearing the search or picking another folder.','search')}
const hl=(t,q)=>q&&t.toLowerCase().includes(q)?t.replace(new RegExp('('+q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','ig'),'<mark>$1</mark>'):t;
ACT.tree=t=>{S.lib.path=t.dataset.arg?t.dataset.arg.split('|'):[];$('#tree').innerHTML=treeHTML(LT.find(x=>x[0]===S.lib.tab)[3]());libRows()};
INP.libQ=t=>{S.lib.q=t.value;libRows()};
const libArr=()=>({videos:VIDS,notes:NOTES,mats:MATS,flash:null})[S.lib.tab];
ACT.libDel=t=>{const a=libArr();if(!a)return toast('Open the stack to delete it');const it=a[+t.dataset.arg];confirmM(`Delete “${it.t}”?`,'Delete',()=>{a.splice(+t.dataset.arg,1);rerender();toast('Deleted')})};
ACT.libEdit=t=>{const a=libArr();if(!a)return toast('Opening stack…');const it=a[+t.dataset.arg];({videos:vidModal,notes:noteModal,mats:matModal})[S.lib.tab](it)};
function siteView(){$('#lbody').innerHTML=`<div class="g2e"><div class="card"><h3>${ic('trophy')}Hall of Fame<span class="chip c-gy" style="margin-left:6px">${HOF.length}</span></h3><form class="inl" data-f="hof"><input class="inp" name="n" placeholder="Student name" required aria-label="Name"><input class="inp" name="y" placeholder="Year (e.g. 2026)" aria-label="Year"><button class="btn p sm">Add</button></form>${HOF.map((h,i)=>`<div class="lrow"><span class="av" style="width:36px;height:36px;font-size:.75rem">${ini(h.n)}</span><div class="lmain"><b>${h.n}</b><small>${h.y}</small></div><div class="lact"><button class="ib sm dng" data-act="hofDel" data-arg="${i}" aria-label="Delete">${ic('trash')}</button></div></div>`).join('')}</div>
<div class="card"><h3>${ic('msg')}Student stories<span class="chip c-gy" style="margin-left:6px">${STORIES.length}</span></h3><form class="inl col" data-f="story"><input class="inp" name="n" placeholder="Student name" required aria-label="Name"><input class="inp" name="c" placeholder="Country" aria-label="Country"><textarea class="inp" name="t" rows="3" placeholder="Story text" required aria-label="Story"></textarea><button class="btn p sm" style="justify-self:start">Add</button></form>${STORIES.map((s,i)=>`<div class="lrow" style="align-items:flex-start"><span class="av" style="width:36px;height:36px;font-size:.75rem">${ini(s.n)}</span><div class="lmain"><b>${s.n} <small style="font-weight:400">${s.c}</small></b><small style="white-space:normal;display:block">${esc(s.t)}</small></div><div class="lact"><button class="ib sm dng" data-act="storyDel" data-arg="${i}" aria-label="Delete">${ic('trash')}</button></div></div>`).join('')}</div></div>`}
document.addEventListener('submit',e=>{const f=e.target.closest('form[data-f]');if(!f)return;e.preventDefault();const d=Object.fromEntries(new FormData(f));if(f.dataset.f==='hof')HOF.unshift({n:d.n,y:d.y?'Class of '+d.y:'—'});else STORIES.unshift({n:d.n,c:d.c||'—',t:d.t});rerender();toast('Added')});
ACT.hofDel=t=>{HOF.splice(+t.dataset.arg,1);rerender()};ACT.storyDel=t=>{STORIES.splice(+t.dataset.arg,1);rerender()};
/* ---------- SCHEDULE ---------- */
const DN=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],DF=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
R.schedule=()=>{const s=S.sch;$('#v-schedule').innerHTML=`<div class="ph pr"><div><span class="eb">Class timetable</span><h1>Schedule</h1></div><button class="btn p" data-act="qSch">${ic('plus')}New schedule</button></div>${seg([['list','Schedules','list',SCHEDS.length],['week','Weekly view','cal']],s.tab,'schTab')}<div id="schb"></div>`;
$('#schb').innerHTML=s.tab==='list'?`<div class="sch-g2">${SCHEDS.map(c=>`<div class="card"><div style="display:flex;align-items:center;gap:8px"><h3 style="margin:0;font-size:1.3rem">${c.name}</h3><span style="margin-left:auto" class="lact"><button class="ib sm" data-act="schEdit" data-arg="${c.id}" aria-label="Edit">${ic('edit')}</button><button class="ib sm dng" data-act="schDel" data-arg="${c.id}" aria-label="Delete">${ic('trash')}</button></span></div><div class="tags2"><span class="chip c-gy">${c.sessions.length} sessions</span><span class="chip c-gy">${c.students.length} students</span>${[...new Set(c.sessions.map(x=>x.d))].sort().map(d=>`<span class="chip c-rd">${DN[d]}</span>`).join('')}</div><div class="tags2">${c.students.map(n=>`<span class="chip c-th">${n}</span>`).join('')}</div><div class="mfoot" style="margin-top:14px;justify-content:stretch"><button class="btn o" style="flex:1" data-act="assign" data-arg="${c.id}">${ic('users')}Assign students</button></div></div>`).join('')}</div>`:`<div class="card"><div class="week" style="grid-template-columns:repeat(7,minmax(0,1fr));gap:8px">${DN.map((d,i)=>`<div class="wd ${i===2?'today':''}"><small>${d}</small>${SCHEDS.flatMap(c=>c.sessions.filter(x=>x.d===i)).map(x=>`<div class="ev ${x.ty==='Theory'?'th':'pr'}"><b>${x.ty}</b>${x.s}${x.tp?`<br>${x.tp}`:''}</div>`).join('')||'<span class="no">—</span>'}</div>`).join('')}</div></div>`};
ACT.schTab=t=>{S.sch.tab=t.dataset.arg;rerender()};
ACT.schDel=t=>confirmM('Delete this schedule?','Delete',()=>{SCHEDS=SCHEDS.filter(c=>c.id!==+t.dataset.arg);rerender();toast('Schedule deleted')});
ACT.schEdit=t=>schModal(SCHEDS.find(c=>c.id===+t.dataset.arg));
ACT.assign=t=>{const c=SCHEDS.find(x=>x.id===+t.dataset.arg),all=STU.map(s=>s.n);let chosen=new Set(c.students);
const draw=()=>{$('#asl').innerHTML=all.filter(n=>n.toLowerCase().includes($('#asq').value.toLowerCase())).map(n=>`<label class="asr"><span class="cb"><input type="checkbox" ${chosen.has(n)?'checked':''} data-n="${esc(n)}"><span></span></span><b>${n}</b></label>`).join('');$('#asc').textContent=`${chosen.size} selected out of ${all.length}`;$('#asb').textContent=`Assign ${chosen.size} students`};
modal(`<div class="mh"><div><h3>Assign students</h3><p class="sub">Schedule: <b style="color:#fff">${c.name}</b></p></div><button class="ib x" aria-label="Close">${ic('x')}</button></div><div class="mbody"><div class="search" style="margin:0 0 10px">${ic('search')}<input id="asq" placeholder="Search students…" aria-label="Search"></div><div style="display:flex;justify-content:space-between;font-size:.85rem;margin-bottom:8px"><span class="sub" id="asc"></span><button class="lk" id="asa" style="color:var(--cr)">Select all</button></div><div id="asl" class="asl"></div><div class="mfoot"><button class="btn o" data-act="closeM">Cancel</button><button class="btn p" id="asb"></button></div></div>`);
draw();$('#asq').oninput=draw;$('#asa').onclick=()=>{all.forEach(n=>chosen.add(n));draw()};$('#asl').onchange=e=>{const n=e.target.dataset.n;e.target.checked?chosen.add(n):chosen.delete(n);$('#asc').textContent=`${chosen.size} selected out of ${all.length}`;$('#asb').textContent=`Assign ${chosen.size} students`};$('#asb').onclick=()=>{c.students=[...chosen];closeM();rerender();toast('Students assigned')}};
