/* ---------- MODALS ---------- */
const PRG=['Microsoft Word','Microsoft PowerPoint','Microsoft Access','Microsoft Excel','Microsoft SharePoint'];
const PRGN={'Microsoft Word':2,'Microsoft PowerPoint':2,'Microsoft Access':4,'Microsoft Excel':4,'Microsoft SharePoint':4};
function hwModal(){const st={sec:'',ph:'',ch:'',pg:'',kind:'',it:''},SC=[10,20,30,40,50,100];
const chip=(k,v,on)=>'<button type="button" class="ch '+(on?'on':'')+'" data-hw="'+k+'" data-v="'+esc(v)+'">'+v+'</button>';
const auto=()=>st.sec==='theory'?st.ch:st.sec==='practical'&&st.pg&&st.it?st.pg.replace('Microsoft ','')+' '+st.it:'';
const dyn=()=>{let h='';if(st.sec==='theory'){h='<div class="hwq"><small>Phase</small><div class="chips">'+PHV.map(p=>chip('ph',p[0],st.ph===p[0])).join('')+'</div></div>';if(st.ph)h+='<div class="hwq"><small>Chapter</small><div class="chips">'+PHV.find(p=>p[0]===st.ph)[1].map(c=>chip('ch',c,st.ch===c)).join('')+'</div></div>'}
else if(st.sec==='practical'){h='<div class="hwq"><small>Program</small><div class="chips">'+PRG.map(p=>chip('pg',p,st.pg===p)).join('')+'</div></div>';if(st.pg){const n=PRGN[st.pg];['Guide','Task'].forEach(k=>{h+='<div class="hwq"><small>'+k+'s</small><div class="chips">'+[...Array(n)].map((_,i)=>chip('it',k+' '+(i+1),st.it===k+' '+(i+1))).join('')+'</div></div>'})}}
else h='<p class="sub" style="margin:0 0 4px">Pick a section to choose the lesson.</p>';$('#hwdyn').innerHTML=h;$('#hwt').placeholder=auto()||'Title (optional)';$$('[data-hw=sec]').forEach(b=>b.classList.toggle('on',b.dataset.v===st.sec))};
const sc=()=>{const v=+$('#hwmax').value;$$('[data-hw=max]').forEach(b=>b.classList.toggle('on',+b.dataset.v===v))};
formModal({title:'Create H.W',sub:'Pick the lesson, set the score, assign',icon:'task',submit:'Create H.W',cls:'wide',body:'<div class="hwq"><small>Section</small><div class="seg2"><button type="button" data-hw="sec" data-v="theory">'+ic('cap')+'Theory</button><button type="button" data-hw="sec" data-v="practical">'+ic('mon')+'Practical</button></div></div><div id="hwdyn"></div>'+fld('Title (optional — auto-filled from your selection)','t','','text','Title (optional)').replace('class="inp"','class="inp" id="hwt"')+'<div class="hwq"><small>Max score</small><div class="chips">'+SC.map(v=>chip('max',v,v===30)).join('')+'<input class="inp" id="hwmax" name="max" type="number" min="1" value="30" placeholder="Custom" style="width:110px;min-height:40px;padding:8px 14px" aria-label="Custom max score"></div></div><div class="r2">'+fld('Due date','due','','datetime-local')+sel('Assign to','to',['All students','Selected students (choose after)'])+'</div>'+area('Instructions (optional)','ins'),
onSubmit:d=>{const t=(d.t||'').trim()||auto();if(!st.sec&&!t)return toast('Pick a section or type a title');if(!t)return toast('Pick a '+(st.sec==='theory'?'chapter':'guide / task')+' or type a title');
ASGS.unshift({t,type:st.sec==='practical'?'task':'classified',sec:st.sec||'theory',due:d.due?new Date(d.due).toLocaleDateString():'—',max:+d.max||0});closeM();rerender();toast('H.W created: '+t)}});
const f=$('#mf');dyn();f.addEventListener('click',e=>{const b=e.target.closest('[data-hw]');if(!b)return;const k=b.dataset.hw,v=b.dataset.v;
if(k==='sec'){st.sec=v;st.ph=st.ch=st.pg=st.kind=st.it=''}else if(k==='ph'){st.ph=v;st.ch=''}else if(k==='ch')st.ch=v;else if(k==='pg'){st.pg=v;st.kind=st.it=''}else if(k==='kind'){st.kind=v;st.it=''}else if(k==='it')st.it=v;else if(k==='max'){$('#hwmax').value=v;sc();return}dyn()});$('#hwmax').addEventListener('input',sc)}
function quizModal(){formModal({title:'Create quiz',sub:'Timed quiz for your students',icon:'cap',submit:'Create quiz',body:`${fld('Title','t','','text','e.g. Test')}<div class="r2">${fld('Duration (min)','dur','10','number')}${fld('Max score','max','30','number')}</div><div class="r2">${sel('Type','type',['theory','practical'])}${fld('Opens at','at','','datetime-local')}</div>${area('Instructions (optional)','ins')}`,onSubmit:d=>{QUIZ.unshift({t:d.t||'Untitled',dur:+d.dur,max:+d.max,type:d.type,assigned:22,done:0});closeM();rerender();toast('Quiz created')}})}
function annModal(){formModal({title:'Create new announcement',icon:'mega',submit:'Create announcement',body:`${fld('Title (5–200 characters)','t')}${area('Content (min. 10 characters)','b')}<div class="r2">${sel('Category','cat',['general','assignment','exam','holiday','meeting','important'])}${sel('Priority','pr',['medium','low','high','urgent'])}</div>${sel('Target audience','aud',['all','students','parents'])}<div class="r2">${fld('Publish date (optional)','pd','','datetime-local')}${fld('Expiry date (optional)','ed','','datetime-local')}</div><label class="cbx"><input type="checkbox" name="pin"> Pin this announcement</label>`,onSubmit:d=>{ANN.unshift({t:d.t||'Untitled',cat:d.cat,pr:d.pr,b:d.b||'',d:new Date().toLocaleString(),aud:d.aud,v:0,pin:!!d.pin});closeM();rerender();toast('Announcement published')}})}
function vidModal(it){const ty=it?it.path[0]:'Theory';formModal({title:it?'Edit video':'Add new video',icon:'play',submit:it?'Save':'Create video',body:`<div class="r2">${fld('Title','t',it?.t||'','text','Enter video title')}${sel('Type','ty',['Theory','Practical','Other'],ty)}</div>${area('Description (optional)','ds')}${fld('Video URL (Google Drive) *','url','','url','https://drive.google.com/file/d/…')}<div class="r2">${sel('Phase (theory)','ph',['Phase 1','Phase 2','Phase 3'],it?.path[1])}${sel('Program (practical)','pg',PRG,it?.path[1])}</div><div class="r2">${fld('Order / chapter','o',it?.order||1,'number')}${sel('Access level','ac',['All students','Standard + Premium','Premium only'])}</div>`,onSubmit:d=>{const path=d.ty==='Theory'?['Theory',d.ph,d.t]:d.ty==='Practical'?['Practical',d.pg]:['Other'];if(it){it.t=d.t||it.t;it.path=path;it.order=+d.o}else VIDS.unshift({t:d.t||'Untitled',path,order:+d.o});closeM();rerender();toast('Video saved')}})}
function noteModal(it){formModal({title:it?'Edit note':'Add new note',sub:'Prezi notes by chapter and phase',icon:'lib',submit:it?'Save':'Create note',body:`<div class="r2">${fld('Title','t',it?.t||'','text','e.g. CH 7 Malware Attacks')}${sel('Phase','ph',['Phase 1','Phase 2','Phase 3'],it?.path[0])}</div>${fld('Prezi link','url',it?.url||'','url','https://prezi.com/…')}${fld('Order (optional)','o',it?.order??0,'number')}`,onSubmit:d=>{const path=[d.ph,d.t||'Untitled'];if(it){it.t=d.t||it.t;it.path=path;it.url=d.url;it.order=+d.o}else NOTES.push({t:d.t||'Untitled',path,order:+d.o,url:d.url});closeM();rerender();toast('Note saved')}})}
function matModal(it){formModal({title:it?'Edit material':'Upload new material',icon:'up',submit:it?'Save':'Upload material',body:`${fld('Title *','t',it?.t||'','text','e.g. Introduction to Programming')}${area('Description (optional)','ds')}${sel('Type','ty',['Theory','Practical','Other'],it?.path[0])}<div class="drop">${ic('up')}<b>Click to select a file</b><small>PDF, Word, PowerPoint, Excel, ZIP · Max 100MB</small></div>${fld('…or external link','url','','url','https://')}`,onSubmit:d=>{if(it){it.t=d.t||it.t;it.path=[d.ty]}else MATS.unshift({t:d.t||'Untitled',path:[d.ty],meta:'0 downloads · today'});closeM();rerender();toast('Material saved')}})}
function flashModal(){let n=1;const card=i=>`<div class="fcd"><b>${i}</b>${area('Front *','f'+i,'','Question or prompt…')}${area('Back *','b'+i,'','Answer or explanation…')}</div>`;
formModal({title:'Create flashcard stack',sub:'A new set of flashcards for your students',icon:'cards',submit:'Create stack',body:`<div class="r2">${fld('Stack title *','t','','text','Enter stack title')}${sel('Visibility','v',['Public','Private'])}</div><div id="fcs">${card(1)}</div><button type="button" class="btn o sm" id="addc">${ic('plus')}Add card</button>`,onSubmit:d=>{FLASH.unshift({t:d.t||'Untitled',cards:n,by:'Ahmad Tamer',kind:'Teacher',studies:0});closeM();rerender();toast('Stack created')}});
$('#addc').onclick=()=>{n++;$('#fcs').insertAdjacentHTML('beforeend',card(n))}}
function schModal(sc){const ss=sc?JSON.parse(JSON.stringify(sc.sessions)):[{d:0,s:'9:00 AM',e:'10:30 AM',ty:'Theory',tp:''}],open=new Set(ss.map(x=>x.d));
const to24=t=>{const m=t.match(/(\d+):(\d+)\s*(AM|PM)/);if(!m)return'09:00';let h=+m[1]%12+(m[3]==='PM'?12:0);return String(h).padStart(2,'0')+':'+m[2]},to12=t=>{const[h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`};
const draw=()=>{$('#days').innerHTML=DF.map((d,i)=>{const l=ss.map((x,k)=>({x,k})).filter(o=>o.x.d===i);return `<div class="acc ${open.has(i)?'':'cl'}"><button type="button" data-act="acc"><span class="n" style="width:34px;height:34px;border-color:var(--bd2);color:var(--mu);font-size:.8rem">${DN[i]}</span><span><h4>${d}</h4><small>${l.length?l.length+' session'+(l.length>1?'s':''):'No sessions'}</small></span><span class="btn g sm" data-add="${i}" style="margin-left:auto;margin-right:8px">${ic('plus')}Add session</span>${ic('down')}</button><div class="bd3"><div>${l.map(o=>`<div class="ses"><label class="fld"><span>Start</span><input class="inp" type="time" value="${to24(o.x.s)}" data-k="${o.k}" data-p="s"></label><label class="fld"><span>End</span><input class="inp" type="time" value="${to24(o.x.e)}" data-k="${o.k}" data-p="e"></label><label class="fld"><span>Type</span><select class="inp" data-k="${o.k}" data-p="ty"><option${o.x.ty==='Theory'?' selected':''}>Theory</option><option${o.x.ty==='Practical'?' selected':''}>Practical</option></select></label><label class="fld"><span>Topic</span><input class="inp" data-k="${o.k}" data-p="tp" value="${esc(o.x.tp)}" placeholder="e.g. Chapter 4"></label><button type="button" class="btn o sm dng" data-rm="${o.k}">Remove</button></div>`).join('')}</div></div></div>`}).join('')};
formModal({title:sc?'Edit schedule':'Create schedule',icon:'cal',submit:sc?'Save schedule':'Create schedule',cls:'wide',body:`<div class="r2">${fld('Schedule name','name',sc?.name||'New Schedule')}${fld('Notes (optional)','notes',sc?.notes||'','text','Additional notes')}</div><div id="days"></div>`,onSubmit:d=>{const list=ss.map(x=>({...x,s:/AM|PM/.test(x.s)?x.s:to12(x.s),e:/AM|PM/.test(x.e)?x.e:to12(x.e)}));if(sc){sc.name=d.name;sc.notes=d.notes;sc.sessions=list}else SCHEDS.push({id:Date.now(),name:d.name,notes:d.notes,sessions:list,students:[]});closeM();rerender();toast('Schedule saved')}});
draw();const root=$('#days');
root.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a){e.stopPropagation();ss.push({d:+a.dataset.add,s:'9:00 AM',e:'10:30 AM',ty:'Theory',tp:''});open.add(+a.dataset.add);draw();return}const r=e.target.closest('[data-rm]');if(r){ss.splice(+r.dataset.rm,1);draw()}},true);
root.addEventListener('input',e=>{const t=e.target;if(t.dataset.k===undefined)return;const v=t.value;ss[+t.dataset.k][t.dataset.p]=(t.dataset.p==='s'||t.dataset.p==='e')?to12(v):v})}
/* ---------- registration + student modals ---------- */
ACT.regDetail=()=>{const r=REGS[0];modal(`<div class="mh"><span class="mi">${ic('user')}</span><div><h3>Registration details</h3><p class="sub">${r.n}</p></div><button class="ib x" aria-label="Close">${ic('x')}</button></div><div class="mbody"><div class="pf"><span class="av" style="width:64px;height:64px;font-size:1.3rem;border-radius:18px">${ini(r.n)}</span><div><h3 style="margin:0">${r.n}</h3><p class="sub">${r.em}</p><span class="chip c-th">Center student</span></div></div><div class="kv">${[['Year / class',r.y],['Nationality',r.country],['City','N/A'],['School',r.sc],['Session',r.ses],['Retaker',r.ret],['Tech knowledge',r.tech+'/10'],['English level','N/A/10']].map(k=>`<div><small>${k[0]}</small><b>${k[1]}</b></div>`).join('')}</div><div class="card" style="margin-top:12px"><small class="lbl">Contact information</small><p style="margin:6px 0">${ic('mail')} ${r.em}</p><p style="margin:0">${ic('phone')} ${r.ph}</p></div><div class="mfoot"><button class="btn o" data-act="closeM">Close</button><button class="btn p" data-act="rejReg">Reject</button><button class="btn g" data-act="apprReg2">Approve</button></div></div>`)};
ACT.apprReg2=()=>{ACT.apprReg();closeM()};
ACT.addStu=()=>formModal({title:'Add new student',icon:'users',submit:'Add student',body:`<div class="r2">${fld('Full name','n')}${fld('Email','em','','email')}</div><div class="r2">${sel('Year','y',['10','11','12'])}${sel('Session','s',['NOV 25','JUN 26'])}</div>${fld('School','sc')}${fld('Phone','ph')}`,onSubmit:d=>{STU.push({i:STU.length,n:d.n||'New student',em:d.em,y:d.y,s:d.s,sc:d.sc||'—',en:new Date().toLocaleDateString(),id:'AT2026'+String(32+STU.length-22).padStart(4,'0'),st:'active',parent:false});closeM();rerender();toast('Student added')}});
let SM={i:0,tab:'sum'};
ACT.viewStu=t=>{SM={i:+t.dataset.arg,tab:'sum'};stuModal()};
ACT.smTab=t=>{SM.tab=t.dataset.arg;stuModal()};
function stuModal(){const x=STU[SM.i],subs=SUBS.filter(s=>s.st===x.n),done=subs.length,plans=PAY[x.n]=PAY[x.n]||[];
const tabs=[['sum','Summary','grid'],['asg','Assignments','task',ASGS.length],['quiz','Quizzes','cap',QUIZ.length],['pay','Payments','star']];
let body='';
if(SM.tab==='sum')body=`<div class="g4" style="margin-bottom:14px">${[['Progress','grid','0%'],['Assignments','task',`${subs.filter(s=>s.status==='graded').length}/${ASGS.length}`],['Quizzes','cap','0/'+QUIZ.length],['Score','trophy',subs.filter(s=>s.score!==undefined).length?Math.round(subs.filter(s=>s.score!==undefined).reduce((a,s)=>a+s.score/s.max,0)/subs.filter(s=>s.score!==undefined).length*100)+'%':'0%']].map(s=>`<div class="stat"><div><small>${ic(s[1])}${s[0]}</small><b>${s[2]}</b></div></div>`).join('')}</div><div class="g2e"><div class="card"><h3>${ic('user')}Personal information</h3><p class="ir">${ic('mail')}${x.em}</p><p class="ir">${ic('cal')}Enrolled: ${x.en}</p><p class="ir">${ic('users')}Parent: ${x.parent?'Linked':'Not set up'}</p></div><div class="card"><h3>${ic('cap')}Academic information</h3>${[['Student ID',x.id],['Year',x.y],['Session',x.s],['School',x.sc]].map(k=>`<div class="kvr"><span>${k[0]}</span><b>${k[1]}</b></div>`).join('')}</div></div>`;
if(SM.tab==='asg')body=`<div class="tbl">${ASGS.map(a=>{const s=subs.find(z=>z.a===a.t);return `<div class="trow"><span class="lic">${ic('task')}</span><div class="lmain"><b>${a.t}</b><small>Due ${a.due} · max ${a.max} · ${a.type}</small></div>${s?`<span class="chip ${s.status==='graded'?'c-pr':'c-am'}">${s.status==='graded'?s.score+'/'+s.max:'Submitted'}</span><button class="btn o sm" data-act="smOpen" data-arg="${s.id}">${ic('eye')}Open submission</button>`:'<span class="chip c-gy">assigned</span>'}</div>`}).join('')}</div>`;
if(SM.tab==='quiz')body=`<div class="tbl">${QUIZ.map(q=>`<div class="trow"><span class="lic">${ic('cap')}</span><div class="lmain"><b>${q.t}</b><small>${q.dur} min · max ${q.max} · ${q.type}</small></div><span class="chip c-gy">assigned</span></div>`).join('')}</div>`;
if(SM.tab==='pay')body=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;gap:8px;flex-wrap:wrap"><h3 style="margin:0">${ic('star')}Payment plans</h3><div style="display:flex;gap:8px"><button class="btn o sm" data-act="resetPw" data-arg="${esc(x.n)}">${ic('key')}Reset password</button><button class="btn p sm" data-act="addPlan">${ic('plus')}Add plan</button></div></div><div id="pform"></div>${plans.length?plans.map((p,k)=>`<div class="trow"><div class="lmain"><b>${p.t} <span class="chip c-gy">${p.kind}</span> <span class="chip ${p.st==='paid'?'c-pr':'c-am'}">${p.st}</span></b><small><b style="color:#fff;font-size:1rem">${p.amt.toLocaleString()} EGP</b> ${p.det||''} · Due ${p.due}</small></div>${p.st==='paid'?'':`<button class="btn g sm" data-act="payOk" data-arg="${k}">${ic('ok')}Mark paid</button>`}<button class="btn o sm dng" data-act="payDel" data-arg="${k}">${ic('x')}Delete</button></div>`).join(''):empty('No payment plans yet.','star')}`;
modal(`<div class="mh big"><span class="av" style="width:60px;height:60px;font-size:1.1rem">${ini(x.n)}</span><div><h3>${x.n}</h3><p class="sub">${x.em}</p><span class="chip c-pr">Approved</span> <span class="chip c-pr">Active</span></div><button class="ib x" aria-label="Close">${ic('x')}</button></div><div class="mtabs">${tabs.map(t=>`<button class="${SM.tab===t[0]?'on':''}" data-act="smTab" data-arg="${t[0]}">${ic(t[2])}${t[1]}${t[3]!==undefined?` (${t[3]})`:''}</button>`).join('')}</div><div class="mbody" style="max-height:60vh;overflow:auto">${body}</div><div class="mfoot" style="padding:0 24px 20px"><button class="btn o" data-act="closeM">Close</button></div>`,'wide')}
ACT.smOpen=t=>{closeM();S.work.tab='subs';S.work.f='all';S.work.asg='All';S.work.lp={sec:'',ph:'',ch:'',pg:''};S.work.stu='All';S.work.sel=+t.dataset.arg;go('work')};
ACT.payOk=t=>{PAY[STU[SM.i].n][+t.dataset.arg].st='paid';stuModal();toast('Marked as paid')};ACT.payDel=t=>{PAY[STU[SM.i].n].splice(+t.dataset.arg,1);stuModal()};
ACT.addPlan=()=>{$('#pform').innerHTML=`<form class="card" id="pf" style="margin-bottom:12px"><small class="lbl" style="color:var(--cr)">NEW PAYMENT PLAN</small><div class="r2">${sel('Plan type','kind',['Monthly','Per Session','One-off'])}${fld('Amount (EGP)','amt','','number','e.g. 500')}</div><div class="r2">${fld('Due date','due','','date')}${fld('Description','t','','text','e.g. November package')}</div><div class="mfoot"><button type="button" class="btn o sm" id="pc">Cancel</button><button class="btn p sm">Save plan</button></div></form>`;$('#pc').onclick=()=>$('#pform').innerHTML='';$('#pf').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!+d.amt)return toast('Enter an amount');PAY[STU[SM.i].n].push({t:d.t||'plan',kind:d.kind,amt:+d.amt,det:'',due:d.due?new Date(d.due).toLocaleDateString():'—',st:'pending'});stuModal()}};
shell();fab();go(localStorage.getItem('at-teacher-v')&&NAV.some(n=>n[0]===localStorage.getItem('at-teacher-v'))?localStorage.getItem('at-teacher-v'):'home');
