/* ---------- WORK ---------- */
const dOk=s=>{const w=S.work;if(!w.from&&!w.to)return true;const d=new Date(s.at.split(' ')[0]);return(!w.from||d>=new Date(w.from+'T00:00'))&&(!w.to||d<=new Date(w.to+'T23:59'))};
const subFiltered=()=>{const w=S.work,q=w.q.toLowerCase();return SUBS.filter(s=>(w.f==='all'||(w.f==='needs'&&s.status==='needs')||(w.f==='graded'&&s.status==='graded')||(w.f==='late'&&s.late))&&lessonOk(s)&&(w.stu==='All'||s.st===w.stu))};
R.work=()=>{const w=S.work;$('#v-work').innerHTML=`<div class="ph pr"><div><span class="eb">Assignments &amp; quizzes</span><h1>Work</h1></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn o" data-act="qQuiz">${ic('cap')}Create quiz</button><button class="btn p" data-act="qHW">${ic('plus')}Create H.W</button></div></div>${seg([['subs','Submissions','dl',needsN().length],['asg','Assignments','task',ASGS.length],['quiz','Quizzes','cap',QUIZ.length]],w.tab,'workTab')}<div id="wbody"></div>`;({subs:subsView,asg:asgView,quiz:quizView})[w.tab]()};
ACT.workTab=t=>{S.work.tab=t.dataset.arg;rerender()};
function subsView(){const w=S.work,asgs=['All',...new Set(SUBS.map(s=>s.a))];
$('#wbody').innerHTML=`<div class="sub-bar"><div class="chips" style="margin:0">${[['needs','Needs grading',SUBS.filter(s=>s.status==='needs').length],['late','Late',SUBS.filter(s=>s.late).length],['graded','Graded',SUBS.filter(s=>s.status==='graded').length],['all','All',SUBS.length]].map(c=>`<button class="ch ${w.f===c[0]?'on':''}" data-act="subF" data-arg="${c[0]}">${c[1]}<em>${c[2]}</em></button>`).join('')}</div>${lpHTML(false)}${spHTML(false)}</div>
<div class="sub-grid ${w.sel?'open':''}"><div class="sub-list card"><div class="sl-h"><label class="cb"><input type="checkbox" data-in="subAll"><span></span>Select all</label><button class="btn o sm" data-act="zip">${ic('zip')}<span id="zipl">Download ${w.chk.size?w.chk.size+' selected':'all'} (zip)</span></button></div><div id="sl" class="sl-b"></div></div><div class="sub-pane card" id="sp"></div></div>`;subList();subPane()}
function subList(){const w=S.work,l=subFiltered();if(!l.find(s=>s.id===w.sel)&&innerWidth>1180)w.sel=l[0]?l[0].id:null;
$('#sl').innerHTML=l.length?l.map(s=>`<div class="sl-r ${s.id===w.sel?'on':''}" data-act="subSel" data-arg="${s.id}"><label class="cb" onclick="event.stopPropagation()"><input type="checkbox" data-in="subChk" data-id="${s.id}" ${w.chk.has(s.id)?'checked':''}><span></span></label><span class="av">${ini(s.st)}</span><div class="sl-m"><b>${s.st}</b><small>${s.a} · ${s.at}</small></div><div class="sl-t">${s.late?'<span class="chip c-rd">Late</span>':''}${s.status==='graded'?`<span class="chip c-pr">${s.score}/${s.max}</span>`:'<span class="chip c-am">Ungraded</span>'}</div></div>`).join(''):empty('No submissions match these filters.','ok');
const z=$('#zipl');if(z)z.textContent=`Download ${w.chk.size?w.chk.size+' selected':'all'} (zip)`}
function subPane(){const w=S.work,s=SUBS.find(x=>x.id===w.sel),p=$('#sp');if(!s){p.innerHTML=empty('Select a submission to preview, download and grade it.','task');return}
const pct=s.status==='graded'?Math.round(s.score/s.max*100):null;
p.innerHTML='<button class="btn o sm back-m" data-act="subBack">'+ic('left')+'Back</button><div class="sp-h"><span class="av" style="width:44px;height:44px">'+ini(s.st)+'</span><div class="lmain"><h3 style="margin:0">'+s.st+'</h3><p class="sub" style="display:flex;gap:6px;align-items:center;flex-wrap:wrap">'+s.a+'<span class="chip '+(s.sec==='theory'?'c-th':'c-pr')+'">'+s.sec+'</span><span class="chip c-gy">'+s.type+'</span></p></div><div class="sp-d"><span>Submitted <b>'+s.at+'</b></span>'+(s.late?'<span class="chip c-rd">Late</span>':'')+'</div></div>'
+'<div class="sp-body"><div class="prev">'+ic('task')+'<p>'+s.files[0][0].split('.').pop().toUpperCase()+' preview</p><small>The file renders here — no need to download first</small></div><div class="sp-side"><div class="files">'+s.files.map(f=>'<div class="file">'+ic('clip')+'<span><b>'+f[0]+'</b><small>'+f[1]+'</small></span><button class="btn o sm" data-act="dlFile" data-arg="'+f[0]+'" aria-label="Download '+f[0]+'">'+ic('dl')+'</button></div>').join('')+'</div>'
+'<div class="grade"><div class="gr-h"><b>Grade</b>'+(pct!==null?'<span class="chip c-pr">'+pct+'%</span>':'')+'</div><div class="gr-i"><input class="inp" id="gsc" type="number" min="0" max="'+s.max+'" placeholder="Score" value="'+(s.score??'')+'" aria-label="Score"><span class="gmax">/ '+s.max+'</span></div><div class="gq">'+[100,75,50].map(q=>'<button type="button" class="ch" data-act="gQuick" data-arg="'+Math.round(s.max*q/100)+'">'+Math.round(s.max*q/100)+'</button>').join('')+'</div><textarea class="inp" id="gfb" rows="3" placeholder="Feedback for the student (optional)">'+esc(s.fb||'')+'</textarea><div class="gr-a"><button class="btn o" data-act="subNext">Skip</button><button class="btn p" data-act="saveGrade">'+ic('ok')+(s.status==='graded'?'Update grade':'Save &amp; next')+'</button></div></div></div></div>'}
ACT.subF=t=>{S.work.f=t.dataset.arg;rerender()};

INP.subChk=t=>{const id=+t.dataset.id;t.checked?S.work.chk.add(id):S.work.chk.delete(id);const z=$('#zipl');z.textContent=`Download ${S.work.chk.size?S.work.chk.size+' selected':'all'} (zip)`};
INP.subAll=t=>{subFiltered().forEach(s=>t.checked?S.work.chk.add(s.id):S.work.chk.delete(s.id));subList()};
ACT.subSel=t=>{S.work.sel=+t.dataset.arg;$$('.sl-r').forEach(r=>r.classList.toggle('on',r.dataset.arg==S.work.sel));$('.sub-grid').classList.add('open');subPane()};
ACT.subBack=()=>{$('.sub-grid').classList.remove('open')};
ACT.zip=()=>{const n=S.work.chk.size||subFiltered().length;toast(`Preparing ${n} submission${n===1?'':'s'} as a .zip…`)};
ACT.dlFile=t=>toast('Downloading '+t.dataset.arg+'…');
ACT.gQuick=t=>{$('#gsc').value=t.dataset.arg};
ACT.saveGrade=()=>{const s=SUBS.find(x=>x.id===S.work.sel),v=$('#gsc').value;if(v===''||+v>s.max||+v<0){toast('Enter a score between 0 and '+s.max);return}
const was=s.status;s.status='graded';s.score=+v;s.fb=$('#gfb').value;toast(`Saved ${s.st}: ${v}/${s.max}`);if(was==='needs')ACT.subNext(null,true);else{subList();subPane()}badges()};
ACT.subNext=(t,silent)=>{const l=subFiltered(),i=l.findIndex(x=>x.id===S.work.sel),n=l.find((x,k)=>k>i&&x.status==='needs')||l.find(x=>x.status==='needs'&&x.id!==S.work.sel);
if(S.work.f==='needs'){S.work.sel=n?n.id:null}else S.work.sel=n?n.id:S.work.sel;if(!n&&innerWidth<=900)$('.sub-grid').classList.remove('open');subList();subPane();badges();const b=$('[data-act=workTab][data-arg=subs] em');if(b)b.textContent=needsN().length};
function asgView(){$('#wbody').innerHTML=`<div class="card"><h3>${ic('task')}Assignments<small class="sub" style="margin-left:auto;font-weight:400">${ASGS.length} total</small></h3><div class="tbl">${ASGS.map(a=>{const sb=SUBS.filter(s=>s.a===a.t),ng=sb.filter(s=>s.status==='needs').length;return `<div class="trow" data-act="asgOpen" data-arg="${esc(a.t)}"><span class="lic">${ic('task')}</span><div class="lmain"><b>${a.t}</b><small>Due ${a.due} · max ${a.max}</small></div><span class="chip ${a.sec==='theory'?'c-th':'c-pr'}">${a.sec}</span><span class="chip c-gy">${a.type}</span><span class="tcount"><b>${sb.length}</b> submitted</span>${ng?`<span class="chip c-am">${ng} to grade</span>`:'<span class="chip c-gy">—</span>'}${ic('right')}</div>`}).join('')}</div></div>`}
ACT.asgOpen=t=>{S.work.tab='subs';S.work.f='all';S.work.lp=lpFor(LES[t.dataset.arg]);S.work.stu='All';S.work.sel=null;rerender()};
function quizView(){$('#wbody').innerHTML=`<div class="card"><h3>${ic('cap')}Quizzes</h3><div class="tbl">${QUIZ.map(q=>`<div class="trow"><span class="lic">${ic('cap')}</span><div class="lmain"><b>${q.t}</b><small>${q.dur} min · max ${q.max}</small></div><span class="chip c-th">${q.type}</span><span class="tcount"><b>${q.done}</b> / ${q.assigned} completed</span><span class="chip c-am">Assigned</span></div>`).join('')}</div></div>`}
/* ---------- STUDENTS ---------- */
const stuF=()=>{const s=S.stu,q=s.q.toLowerCase();return STU.filter(x=>(!q||(x.n+x.id+x.em).toLowerCase().includes(q))&&(s.ses==='All'||x.s===s.ses)&&(s.yr==='All'||x.y===s.yr)&&(s.st==='All'||x.st===s.st))};
R.students=()=>{const s=S.stu,pend=REGS.filter(r=>r.status==='pending').length;$('#v-students').innerHTML=`<div class="ph pr"><div><span class="eb">Student management</span><h1>Students</h1></div><button class="btn p" data-act="addStu">${ic('plus')}Add new student</button></div>${seg([['list','All students','users',STU.length],['regs','Registrations','bell',pend||'']],s.tab,'stuTab')}<div id="sbody"></div>`;s.tab==='list'?stuList():regList()};
ACT.stuTab=t=>{S.stu.tab=t.dataset.arg;rerender()};
function stuList(){const s=S.stu,opt=(a,v)=>`<option${a===v?' selected':''}>${a}</option>`;$('#sbody').innerHTML=`<div class="fbar"><div class="search" style="margin:0;flex:1;min-width:200px">${ic('search')}<input data-in="stuQ" placeholder="Search name, ID or email…" value="${esc(s.q)}" aria-label="Search students"></div><select class="inp sel-s" data-in="stuSes" aria-label="Session">${[['All','All sessions'],['NOV 25','Session: NOV 25'],['JUN 26','Session: JUN 26']].map(a=>`<option value="${a[0]}"${a[0]===s.ses?' selected':''}>${a[1]}</option>`).join('')}</select><select class="inp sel-s" data-in="stuYr" aria-label="Year">${[['All','All years'],['10','Year 10'],['11','Year 11'],['12','Year 12']].map(a=>`<option value="${a[0]}"${a[0]===s.yr?' selected':''}>${a[1]}</option>`).join('')}</select><select class="inp sel-s" data-in="stuSt" aria-label="Status">${[['All','All statuses'],['active','Status: Active'],['pending','Status: Pending']].map(a=>`<option value="${a[0]}"${a[0]===s.st?' selected':''}>${a[1]}</option>`).join('')}</select></div><div class="card" style="padding:8px"><div id="stl"></div></div>`;stuRows()}
function stuRows(){const l=stuF();$('#stl').innerHTML=l.length?l.map(x=>`<div class="srow2"><span class="av" style="width:42px;height:42px">${ini(x.n)}</span><div class="lmain"><b>${x.n} ${x.st==='pending'?'<span class="chip c-am">Pending</span>':''}</b><small>${x.id}${x.y!=='—'?` · Year ${x.y} · ${x.s}`:''}</small></div><span class="sc-c">${x.sc}</span><span class="en-c">${x.en}</span><div class="sr-a"><button class="btn o sm" data-act="viewStu" data-arg="${x.i}">${ic('eye')}View</button><div class="mw"><button class="ib sm" data-act="menu" data-menu aria-label="More">${ic('dots')}</button><div class="menu">${x.parent?`<button data-act="toastA" data-arg="Opening parent account…">View parent</button><button data-act="goChatP">Chat with parent</button>`:`<button data-act="toastA" data-arg="Parent account created for ${esc(x.n)}">Create parent</button>`}<button data-act="resetPw" data-arg="${esc(x.n)}">Reset password</button><button class="dng" data-act="rmStu" data-arg="${x.i}">Remove</button></div></div></div></div>`).join(''):empty('No students match.','users')}
INP.stuQ=t=>{S.stu.q=t.value;stuRows()};INP.stuSes=t=>{S.stu.ses=t.value;stuRows()};INP.stuYr=t=>{S.stu.yr=t.value;stuRows()};INP.stuSt=t=>{S.stu.st=t.value;stuRows()};
ACT.toastA=t=>toast(t.dataset.arg);ACT.goChatP=()=>{S.inb.tab='chat';S.inb.chat='p';go('inbox')};ACT.resetPw=t=>toast('Reset link sent to '+t.dataset.arg);
ACT.rmStu=t=>{const x=STU[+t.dataset.arg];confirmM(`Remove ${x.n}?`,'Remove',()=>{x.st='removed';STU.splice(+t.dataset.arg,1);STU.forEach((y,i)=>y.i=i);rerender();toast('Student removed')})};
function regList(){const l=REGS.filter(r=>r.status==='pending');$('#sbody').innerHTML=l.length?l.map(r=>`<div class="card reg"><span class="av" style="width:56px;height:56px;font-size:1.1rem">${ini(r.n)}</span><div class="lmain"><h3 style="margin:0">${r.n}</h3><p class="sub">${r.em}</p><div class="rg-m"><span>${ic('cap')}${r.y}</span><span>${ic('pin')}${r.country}</span><span>${ic('clock')}${r.date}</span><span>${ic('phone')}${r.ph}</span></div><div class="rg-f"><div><small>School</small><b>${r.sc}</b></div><div><small>Session</small><b>${r.ses}</b></div><div><small>Tech</small><b>${r.tech}</b></div><div><small>Retaker</small><b>${r.ret}</b></div></div></div><div class="rg-a"><button class="btn o" data-act="regDetail">${ic('eye')}View</button><button class="btn g" data-act="apprReg">${ic('ok')}Approve</button><button class="btn p" data-act="rejReg">${ic('no')}Reject</button></div></div>`).join(''):empty('No pending registrations.','ok')}
ACT.rejReg=()=>confirmM('Reject this registration?','Reject',()=>{REGS.forEach(r=>r.status='rejected');rerender();toast('Registration rejected')});

/* pickers */
const LP0=()=>({sec:'',ph:'',ch:'',pg:''});
const lpFor=l=>{if(!l)return LP0();if(PRG.includes(l))return{sec:'practical',ph:'',ch:'',pg:l};const p=PHV.find(p=>p[1].includes(l));return p?{sec:'theory',ph:p[0],ch:l,pg:''}:LP0()};
const lpLabel=()=>{const l=S.work.lp;return!l.sec?'All lessons':l.sec==='theory'?['Theory',l.ph,l.ch].filter(Boolean).join(' › '):['Practical',l.pg].filter(Boolean).join(' › ')};
function lessonOk(s){const l=S.work.lp;if(!l.sec)return true;if(l.sec==='theory'){if(s.sec!=='theory')return false;if(l.ch)return s.lesson===l.ch;if(l.ph)return PHV.find(p=>p[0]===l.ph)[1].includes(s.lesson);return true}if(s.sec!=='practical')return false;return!l.pg||s.lesson===l.pg}
const pkc=(k,v,on,t)=>'<button type="button" class="ch '+(on?'on':'')+'" data-act="lp" data-k="'+k+'" data-v="'+esc(v)+'">'+(t||v)+'</button>';
function lpHTML(open){const l=S.work.lp;let h='<div class="pkq"><small>Section</small><div class="chips">'+pkc('sec','',!l.sec,'All')+pkc('sec','theory',l.sec==='theory','Theory')+pkc('sec','practical',l.sec==='practical','Practical')+'</div></div>';
if(l.sec==='theory'){h+='<div class="pkq"><small>Phase</small><div class="chips">'+pkc('ph','',!l.ph,'All phases')+PHV.map(p=>pkc('ph',p[0],l.ph===p[0])).join('')+'</div></div>';if(l.ph)h+='<div class="pkq"><small>Chapter</small><div class="chips">'+pkc('ch','',!l.ch,'All chapters')+PHV.find(p=>p[0]===l.ph)[1].map(c=>pkc('ch',c,l.ch===c)).join('')+'</div></div>'}
if(l.sec==='practical')h+='<div class="pkq"><small>Program</small><div class="chips">'+pkc('pg','',!l.pg,'All programs')+PRG.map(p=>pkc('pg',p,l.pg===p)).join('')+'</div></div>';
return '<div class="pk" id="lp"><button class="pkb" data-act="pkT" data-arg="lp">'+ic('lib')+'<span>'+lpLabel()+'</span>'+ic('down')+'</button><div class="pkp'+(open?' on':'')+'">'+h+'<div class="pkf"><button type="button" class="btn o sm" data-act="lpClear">Clear</button><button type="button" class="btn p sm" data-act="pkDone">Done</button></div></div></div>'}
const spRows=q=>{const w=S.work,l=[...STU].sort((x,y)=>x.n.localeCompare(y.n)).filter(x=>x.n.toLowerCase().includes(q.toLowerCase()));return(!q?'<button class="pko '+(w.stu==='All'?'on':'')+'" data-act="spPick" data-arg="All">'+ic('users')+'All students</button>':'')+l.map(x=>'<button class="pko '+(w.stu===x.n?'on':'')+'" data-act="spPick" data-arg="'+esc(x.n)+'"><span class="av" style="width:30px;height:30px;font-size:.7rem">'+ini(x.n)+'</span>'+x.n+'<small>'+SUBS.filter(s=>s.st===x.n).length+'</small></button>').join('')||'<p class="sub" style="padding:10px">No student found.</p>'};
function spHTML(open){const w=S.work;return '<div class="pk" id="sp2"><button class="pkb" data-act="pkT" data-arg="sp2">'+ic('user')+'<span>'+(w.stu==='All'?'All students':w.stu)+'</span>'+ic('down')+'</button><div class="pkp'+(open?' on':'')+'"><div class="search" style="margin:0 0 8px">'+ic('search')+'<input id="spq" data-in="spq" placeholder="Search students…" aria-label="Search students" autocomplete="off"></div><div class="pkl" id="spl">'+spRows('')+'</div></div></div>'}
const pkRefresh=()=>{subList();subPane()};
ACT.pkT=t=>{const p=$('#'+t.dataset.arg+' .pkp'),on=p.classList.contains('on');$$('.pkp.on').forEach(x=>x.classList.remove('on'));if(!on){p.classList.add('on');const i=$('input',p);if(i)i.focus()}};
ACT.pkDone=()=>$$('.pkp.on').forEach(x=>x.classList.remove('on'));
ACT.lp=t=>{const l=S.work.lp,k=t.dataset.k,v=t.dataset.v;if(k==='sec'){l.sec=v;l.ph=l.ch=l.pg='';}else if(k==='ph'){l.ph=v;l.ch=''}else l[k]=v;const done=(k==='ch'||k==='pg')&&v;$('#lp').outerHTML=lpHTML(!done);pkRefresh()};
ACT.lpClear=()=>{S.work.lp=LP0();$('#lp').outerHTML=lpHTML(true);pkRefresh()};
INP.spq=t=>{$('#spl').innerHTML=spRows(t.value)};
ACT.spPick=t=>{S.work.stu=t.dataset.arg;$('#sp2').outerHTML=spHTML(false);pkRefresh()};
document.addEventListener('click',e=>{if(!e.target.closest('.pk'))$$('.pkp.on').forEach(x=>x.classList.remove('on'))});
