const regF=$('#pup'),regPanes=$$('.rp',regF),regDots=$$('.rsteps li'),regNames=['Personal info','Academic journey','Contact info','Skills assessment'];let regStep=0;
const rv=n=>(regF.elements[n]&&regF.elements[n].value||'').trim(),rchk=n=>{const e=regF.querySelector(`[name="${n}"]:checked`);return e?e.value:''};
function regErr(n,msg){const g=regF.querySelector(`[data-g="${n}"]`);const s=regF.querySelector(`.ferr[data-for="${n}"]`);if(s)s.textContent=msg||'';if(g)g.classList.toggle('bad',!!msg);return!!msg}
const phOk=v=>/^\+?[\d\s-]{8,15}$/.test(v);
const regSchool=()=>rchk('stype')==='royal'?'The Royal College School · '+rchk('cls'):rv('school')+' · Year '+rchk('year')+' · '+rchk('session');
const mk=()=>{const e=[];return[e,(n,bad,m)=>{if(regErr(n,bad?m:''))e.push(n)}]};
const VAL=[()=>{const[e,c]=mk();c('fn',!rv('fn'),'Enter your first name');c('ln',!rv('ln'),'Enter your last name');c('em',!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(rv('em')),'Enter a valid email address');c('pw',rv('pw').length<8,'Password must be at least 8 characters');c('pw2',!rv('pw2')||rv('pw2')!==rv('pw'),'Passwords do not match');return e},
()=>{const[e,c]=mk();const royal=rchk('stype')==='royal';c('stype',!rchk('stype'),'Choose your school type');if(rchk('stype')){if(royal)c('cls',!rchk('cls'),'Select your class');else{c('year',!rchk('year'),'Select your year');c('session',!rchk('session'),'Select your session');c('school',!rv('school'),'Enter your school name');c('nat',!rv('nat'),'Select your nationality')}}return e},
()=>{const[e,c]=mk();c('ph',!phOk(rv('ph')),'Enter a valid phone number');c('pph',!phOk(rv('pph')),'Enter a valid parent phone number');if(rchk('stype')==='other'){c('city',!rv('city'),'Enter your city');c('country',!rv('country'),'Enter your country')}return e},
()=>{const[e,c]=mk();c('terms',!regF.elements.terms.checked,'Please accept to continue');return e}];
function regSec(){const t=rchk('stype');$('#sec-royal').classList.toggle('show',t==='royal');$('#sec-other').classList.toggle('show',t==='other');$('#sec-common').classList.toggle('show',t==='other');$('#sec-loc').classList.toggle('show',t==='other');$('#sec-extra').classList.toggle('show',t==='other')}
function regGo(n){regStep=Math.max(0,Math.min(3,n));regPanes.forEach((p,i)=>p.classList.toggle('on',i===regStep));regDots.forEach((d,i)=>{d.classList.toggle('on',i===regStep);d.classList.toggle('done',i<regStep);$('i',d).textContent=i<regStep?'✓':i+1});$('#rbar').style.width=((regStep+1)/4*100)+'%';$('#prev').style.visibility=regStep?'visible':'hidden';$('#next').firstChild.textContent=regStep===3?'Create account ':'Next ';if(regStep===3)regReview();const m=$('#auth');m.scrollTo&&m.scrollTo({top:0})}
function regReview(){const x=s=>String(s).replace(/</g,'&lt;');$('#rev').innerHTML=`<b>Review</b><div><span>Name</span>${x(rv('fn'))} ${x(rv('ln'))}</div><div><span>Email</span>${x(rv('em'))}</div><div><span>School</span>${x(regSchool())}</div>${rchk('stype')==='other'?`<div><span>Location</span>${x(rv('city'))}, ${x(rv('country'))}</div>`:`<div><span>Phone</span>${x(rv('ph'))}</div>`}`}
function regReset(){regHideDone();regGo(0)}
function regHideDone(){$('#regdone').classList.remove('on');$('#regpop').classList.remove('show');$('#auth .tabs').style.display=''}
$('#next').onclick=()=>{const bad=VAL[regStep]();if(bad.length){const el=regF.querySelector(`[name="${bad[0]}"]`);el&&el.focus&&el.focus();return}if(regStep<3)regGo(regStep+1);else regFinish()};
$('#prev').onclick=()=>regGo(regStep-1);
regF.addEventListener('input',e=>{const n=e.target.name;if(n)regErr(n,'');if(n==='pw')pwMeter();if(n==='tech'||n==='eng'){$('#'+n+'v').textContent=e.target.value;e.target.style.setProperty('--p',(e.target.value-1)/9*100+'%')}});
regF.addEventListener('change',e=>{if(e.target.name){regErr(e.target.name,'');if(e.target.name==='stype')regSec()}});
regF.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.tagName!=='BUTTON'){e.preventDefault();$('#next').click()}});
$('.pwt',regF).onclick=e=>{const i=regF.elements.pw,s=i.type==='password';i.type=s?'text':'password';e.currentTarget.setAttribute('aria-label',s?'Hide password':'Show password')};
function pwMeter(){const v=regF.elements.pw.value;let s=0;if(v.length>=8)s++;if(/[A-Z]/.test(v)&&/[a-z]/.test(v))s++;if(/\d/.test(v))s++;if(/[^A-Za-z0-9]/.test(v)||v.length>=12)s++;const col=['#fb7185','#fbbf24','#a3e635','#34d399'][Math.max(0,s-1)];$$('#pstr i').forEach((b,i)=>{b.classList.toggle('on',i<s);b.style.setProperty('--c',col)});$('#phint').textContent=v?['','Weak','Okay','Good','Strong'][s]||'Weak':'Use 8+ characters with letters and numbers.'}
function regFinish(){for(let i=0;i<4;i++){const bad=VAL[i]();if(bad.length){regGo(i);return}}
const first=rv('fn');$('#rdh').textContent=`Congratulations, ${first}!`;$('#rds').textContent=`Your registration (${regSchool()}) has been received.`;$('#rpp').innerHTML=`Your account is <b>pending approval</b>. Please wait for the admin to confirm it — we'll contact you at <b>${rv('em').replace(/</g,'&lt;')}</b> and on WhatsApp (<b>${rv('ph').replace(/</g,'&lt;')}</b>), usually within 24 hours.`;
regF.classList.remove('on');$('#auth .tabs').style.display='none';$('#regdone').classList.add('on');confetti();setTimeout(()=>$('#regpop').classList.add('show'),1500);$('#rgot').focus&&setTimeout(()=>$('#rgot').focus(),1600)}
$('#rgot').onclick=()=>{close();regF.reset();pwMeter();$('#techv').textContent='5';$('#engv').textContent='5';regSec();regHideDone();regGo(0)};
function confetti(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const cv=$('#confetti'),ctx=cv.getContext('2d'),dpr=Math.min(devicePixelRatio||1,2);cv.style.display='block';cv.width=innerWidth*dpr;cv.height=innerHeight*dpr;ctx.scale(dpr,dpr);
const cols=['#CA133E','#DC9F0E','#F1C44F','#FFFFFF','#ff5a7c','#A01030'],P=[],r=$('#auth .auth').getBoundingClientRect();
const burst=(x,y,n,a0,a1,v0,v1)=>{for(let i=0;i<n;i++){const a=(a0+Math.random()*(a1-a0))*Math.PI/180,v=v0+Math.random()*(v1-v0);P.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,w:5+Math.random()*7,h:3+Math.random()*5,rot:Math.random()*6,vr:(Math.random()-.5)*.35,c:cols[i%cols.length],round:Math.random()<.25,t:0})}};
burst(r.left+r.width/2,r.top+120,150,-160,-20,6,17);setTimeout(()=>{burst(0,innerHeight*.8,70,-80,-35,10,19);burst(innerWidth,innerHeight*.8,70,-145,-100,10,19)},350);setTimeout(()=>burst(innerWidth/2,-10,80,60,120,2,6),900);
const tEnd=performance.now()+1400;(function f(){ctx.clearRect(0,0,innerWidth,innerHeight);let alive=0;P.forEach(p=>{p.vy+=.28;p.vx*=.992;p.vy*=.992;p.x+=p.vx;p.y+=p.vy;p.rot+=p.vr;p.t++;if(p.y<innerHeight+30){alive++;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot);ctx.globalAlpha=Math.max(0,1-p.t/260);ctx.fillStyle=p.c;if(p.round){ctx.beginPath();ctx.arc(0,0,p.h/1.2,0,7);ctx.fill()}else ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);ctx.restore()}});if(alive||performance.now()<tEnd)requestAnimationFrame(f);else{ctx.clearRect(0,0,innerWidth,innerHeight);cv.style.display='none'}})()}
regSec();regGo(0);
